version: '2'
services:
  server:
    network_mode: host
    container_name: chatServer
    image: nadaptive/be_training:server
    environment:
      - CHAT_APP
    ports:
      - "50051:50051"

  client_1:
    network_mode: host
    container_name: clientOne
    image: nadaptive/be_training:latest
    environment:
      - CHAT_APP
    tty: true
    stdin_open: true

  client_2:
    network_mode: host
    container_name: clientTwo
    image: nadaptive/be_training:latest
    environment:
      - CHAT_APP
    tty: true
    stdin_open: true



